# See https://github.com/repository-settings

repository:
  # The name of the repository. Changing this will rename the repository
  name: { { gh-repo-name } }

  # A short description of the repository that will show up on GitHub
  description: { { package_description } }

  # A URL with more information about the repository
  homepage: https://rust-wrapbin.github.io/

  # A comma-separated list of topics to set on the repository
  topics: rust

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: false

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: false

labels:
  - name: bug
    description: 🪲 A defect found in the system implementation.

  - name: feature
    description: 🎊 New feature request.

  - name: documentation
    description: 📖 Improvements or additions to documentation.

  - name: test
    description: 🧪 Add or improve tests.

  - name: help wanted
    description: 🙋 Extra attention is needed.

  - name: good first issue
    description: 👶 Good for newcomers.

  - name: discussion
    description: 💬 Further discussion is required.

  - name: security
    description: 🔒 Vulnerability in the code or infrastructure.

  - name: critical
    description: 🚨 Critical issue that needs immediate attention.

  - name: specification
    description: 📐 Improvements or additions to specifications.
