name: mdbook to pages

on:
  push:
    branches: 
      - book

  pull_request:
    branches: 
      - book

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash
    working-directory: ./doc/book

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/book